#!/bin/bash
# build script utilizing multi-brunch
# http://gerrit.aokp.co/#/c/14560/2
#
devices=$*
. build/envsetup.sh
for i in ${devices}; do
    brunch $i
done
for i in ${devices}; do
    mkdir -p ~/www/${i}
    find out/target/product/${i} -name aokp_${i}_\*_unofficial_\*.zip -exec cp {} ~/www/${i}/ \;
done
