#!/bin/bash

#grab this repo
curl -L -o .repo/local_manifests/local_manifest.xml -O -L https://raw.github.com/elelinux/local_manifest/master/default.xml

repo sync -j20

if [ ! -e .symlinked ]; then
touch .symlinked
echo " Symlinking scripts: picks.sh, and compile"
ln -s local_manifest/picks.sh picks.sh
ln -s local_manifest/build multibrunch
ln -s local_manifest/helper_functions helper_functions
echo " making executable"
chmod a+x picks.sh
chmod a+x compile
chmod a+x helper_functions
else
echo " Scripts already setup."
fi
