#!/bin/bash
# Update_forks helper script
# Will return 1 or 0 which will be used if called from sync
#set -x

# Allow history command to be executed
HISTFILE=~/.bash_history
set -o history

LOCAL_MANIFEST=.repo/local_manifests/local_manifest.xml
REMOTE=bmc

DIE_REF=$1

# Initialize helper functions
. helper_functions

if [ "$DIE_REF" = "--resume" ]; then
	echo "Continuing merge...."
	git commit -a
	cd $ROOT
elif [ "$DIE_REF" = "--abort" ]; then
	echo "Aborting merge...."
	git reset --hard aokp/kitkat
	cd $ROOT
	exit 0;
fi

[ -e ${LOCAL_MANIFEST} ] || exit 0
grep ${REMOTE} ${LOCAL_MANIFEST} | cut -f2 -d '"' | sed 1d | while read line; do
	if [ $line != local_manifest ]; then
		echo cd $line
		cd $line
		# check if HEAD matches
		OUR_HEAD=${get_our_head}
		THEIR_HEAD=${get_their_head}
		if [ ${OUR_HEAD} != ${THEIR_HEAD} ]; then
			# We'll then we want better HEAD damnit
			git pull aokp kitkat >/dev/null 2>&1
			#Check HEAD to verify clean merge
			if [ ${OUR_HEAD} != ${get_our_head} ]; then
				# Merge was not clean; allow fixxor
				die_dialog
			fi
		fi
		cd $ROOT
	fi
done

# all merged; time to sync
exit 1
